name: upload & download artifacts

on: 
  workflow_dispatch: # manual triggering

jobs:
    build:
        defaults:
          run:
            working-directory: .api
        name: dotnet release build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: dotnet --list-runtimes
          - run: dotnet --list-sdks
          - run: dotnet build --configuration Release
          - run: dotnet test
          - name: upload-api-single-file
            uses: actions/upload-artifact@v4
            with:
              name: api_exe
              path: ./api/**/bin/Release/**/api.exe

        
