name: upload & download artifacts

on: 
  workflow_dispatch: # manual triggering

env:
  APP_NAME: GHA_PRACTICE

jobs:
    build:
        defaults:
          run:
            working-directory: ./api
        name: dotnet release build & upload
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: dotnet --list-runtimes
          - run: dotnet --list-sdks
          - run: dotnet build --configuration Release
          - run: dotnet test
        #   - run: ls -R
          - name: upload-api-single-file
            id: upload-api-single-file
            uses: actions/upload-artifact@v4
            with:
              name: api_dll
              path: ./api/**/bin/Release/**/api.dll
              include-hidden-files: true

          - name: Print Artifact Files
            run: ls -R
          - name: Output artifact ID
            run:  echo 'Artifact ID is ${{ steps.upload-api-single-file.outputs.artifact-id }}'
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              name: api_dll
              path: ./download_artifact
          - name: Print Artifact Files
            run: ls -R
            working-directory: ./download_artifact
    # deploy:
    #     name: download artifact
    #     runs-on: ubuntu-latest
    #     needs: 
    #       - build
    #     steps:
    #       - name: Download Artifact
    #         uses: actions/download-artifact@v4
    #         with:
    #           name: api_dll
    #           path: '.'
    #       - name: Print Artifact Files
    #         run: ls -R

        
