name: dump-contexts

on:
    workflow_dispatch: 

jobs:
    printGithubContext:
        runs-on: ubuntu-latest
        env:
            key_one: "value_one"
        steps:
            - name: print github context
              env:
                GITHUB_CONTEXT: ${{toJson(github)}}
              run: echo $GITHUB_CONTEXT
            - name: print github context2
              env:
                GITHUB_CONTEXT2: ${{toJson(github)}}
              run: echo $GITHUB_CONTEXT2
            - name: print SECTRETS context
              env:
                SECRETS_CONTEXT: ${{toJson(secrets)}}
              run: echo $SECRETS_CONTEXT
            - name: Dump job context
              env:
                JOB_CONTEXT: ${{ toJson(job) }}
              run: |
                echo "$JOB_CONTEXT"
                echo "$GITHUB_CONTEXT"
            - name: Dump steps context
              env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"
            - name: Dump runner context
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
            - name: Show default environment variables
              run: |
                echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
                echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
                echo "The run id is: $GITHUB_RUN_ID"
                echo "The GitHub Actor's username is: $GITHUB_ACTOR"
                echo "GitHub SHA: $GITHUB_SHA"   
            - name: Dump complete environment variables of the runner machine
              run: env           
            - name: Dump strategy context
              env:
                STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              run: echo "$STRATEGY_CONTEXT"
            - name: Dump matrix context
              env:
                MATRIX_CONTEXT: ${{ toJson(matrix) }}
              run: echo "$MATRIX_CONTEXT"

