name: practice-flow-for-understanding-contexts

on:
    workflow_dispatch: 

jobs:
    printGithubContext:
        runs-on: ubuntu-latest
        env:
            key_one: "value_one"
        steps:
            - name: print github context
              env:
                GITHUB_CONTEXT: ${{toJson(github)}}
              run: echo $GITHUB_CONTEXT