name: environment-and-output

on: 
    workflow_dispatch: 

jobs:
    set_env_variables:
        runs-on: ubuntu-latest
        steps:
            - name: "step1: Set environment variable STEP_ONE_ENV_VAR"
              id: step1
              run: |
                env | sort
                echo "STEP_ONE_ENV_VAR=STEP_ONE_ENV_VALUE" >> $GITHUB_ENV
                echo "GITHUB_ENV of step1:= $GITHUB_ENV"
                echo "updated GITHUB_ENV file of STEP1: $(cat $GITHUB_ENV)"
                env | sort
            - name: 'step2 - Use environment variable setup in the previous step of the same job'
              id: step2
              run: |
                env | sort
                echo "The value of STEP_ONE_ENV_VAR is $STEP_ONE_ENV_VAR"
                echo "STEP_TWO_ENV_VAR=STEP_TWO_ENV_VALUE" >> $GITHUB_ENV
                echo "GITHUB_ENV of step2:= $GITHUB_ENV"
                echo "updated GITHUB_ENV file of STEP2: $(cat $GITHUB_ENV)"
                env | sort
            - name: 'step3: Use environment variable setup in the previous step of the same job again'
              id: step3
              run: |
                echo ${{ env.STEP_ONE_ENV_VAR }}  : # this works
                echo "STEP_3_ENV_VAR=STEP_3_ENV_VALUE" >> $GITHUB_ENV
                echo "GITHUB_ENV of step3:= $GITHUB_ENV"
            - id: step4
              name: set github_env_path variable into $GITHUB_ENV
              run: |
                echo "github_env_path=$GITHUB_ENV" >>$GITHUB_ENV
                echo "GITHUB_ENV of step4:= $GITHUB_ENV"
            - id: step5
              name: printing "$GITHUB_ENV" file PATH
              run: |
                echo "GITHUB_ENV of step4:= ${{env.github_env_path}}"
                echo "GITHUB_ENV of step5:= $GITHUB_ENV"
            - name: print "$GITHUB_ENV" file content
              id: step6
              run: echo "$(cat ${{env.github_env_path}})" 
            - id: step7
              name: accessing all previously defined Environment variables of the current job
              run: |
                echo "The value of STEP_ONE_ENV_VAR is $STEP_ONE_ENV_VAR"
                echo "The value of github_env_path is $github_env_path"                        
    set_env_variables_2:
        runs-on: ubuntu-latest
        steps:
        - name: Store build timestamp
          run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV

        - name: Deploy using stored timestamp
          run: echo "Deploying at $BUILD_TIME"    
        - name: Set the value
          id: step_one
          run: |
            echo "action_state=yellow" >> "$GITHUB_ENV"
        - name: Use the value
          id: step_two
          run: |
            printf '%s\n' "$action_state" # This will output 'yellow'       
            
        - name: Set the value in bash
          id: step_three
          run: |
            {
                echo 'JSON_RESPONSE<<EOF'
                curl https://example.com
                echo EOF
            } >> "$GITHUB_ENV"
        - name: print multi-line env value
          run: echo "$JSON_RESPONSE"

        - name: run multiline command
          run: |
            {
                echo "print1"
                echo "print2"
            }

    one_line_env_variable:
        runs-on: ubuntu-latest
        steps:
        - name: Defining a new Environment Variable
          run: |                          
            ONE_LINE_TEXT="This is a one-line text"
            echo "ONE_LINE_TEXT_ENV_VAR=$ONE_LINE_TEXT" >> $GITHUB_ENV
            
        - name: Using the previously defined environment variable
          run: |
            echo ${{ env.ONE_LINE_TEXT_ENV_VAR }}            
            
    multi_line_env_variable:
        runs-on: ubuntu-latest
        steps:
        - name: Defining a new Environment Variable
          run: |                          
            MULTI_LINES_TEXT="this is line one \n
                                this is line two \n
                                this is line three \n"    
            {
                echo "MULTI_LINES_TEXT_ENV_VAR<<XYZ"
                # here we can place the command that will generate multi-line text
                echo $MULTI_LINES_TEXT
                echo "XYZ"
            } >> $GITHUB_ENV
            
        - name: Using the previously defined environment variable
          run: |
            echo "multi-line-variable is: ${{ env.MULTI_LINES_TEXT_ENV_VAR }}"
            echo "${{env.MULTI_LINES_TEXT_ENV_VAR}}"
            echo ${{env.MULTI_LINES_TEXT_ENV_VAR}}
    set_output_variable:
        runs-on: ubuntu-latest
        steps:
        - name: Set color
          id: color-selector
          run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
        - name: Get color
          env:
            SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
          run: echo "The selected color is $SELECTED_COLOR"     
        - name: Get color directly from previous step's output
          run: echo "The selected color is ${{ steps.color-selector.outputs.SELECTED_COLOR }}"        