name: workflow_expressions
on: workflow_dispatch

env:
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myHexNumber: ${{ 0xff }}
  myExponentialNumber: ${{ -2.99e-2 }}
  myString: Mona the Octocat
  myStringInBraces: ${{ 'It''s open source!' }}
  isMainBranch: ${{ github.ref == 'refs/heads/main' }}
  isFeatureBranch: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
  isDevelopBranch: ${{ github.ref == 'refs/heads/develop' }}
  isActorDependaBot: ${{ github.actor == 'dependabot[bot]' }}
  isMainOrDevOrFeature: ${{ (github.ref == 'refs/heads/main' || 
           github.ref == 'refs/heads/develop' || 
             startsWith(github.ref, 'refs/heads/feature/')) }}
  should_Deploy: >- 
    ${{ (github.ref == 'refs/heads/main' || 
      github.ref == 'refs/heads/develop' || 
      startsWith(github.ref, 'refs/heads/feature/')) &&
      github.actor != 'dependabot[bot]'}}
  condition_value: >- # Use >- or |- for trimmed output
    ${{
      (true ||
        false ||
          false) &&
          false
    }}

jobs:
  conditional_job:
    # ENV CONTEXT IS NOT AVAILABLE IN JOB CONDITION, BUT AVAILABLE IN STEP CONDITION
    if: |-
      ${{ (github.ref == 'refs/heads/main' || 
      github.ref == 'refs/heads/develop' || 
        startsWith(github.ref, 'refs/heads/feature/')) &&
        (github.actor != 'dependabot[bot]')}}

    runs-on: ubuntu-latest
    steps:
      - name: Run a step
        if: ${{ !fromJson(env.isActorDependaBot) }}
        run: echo "This step runs if the condition is met"    
      - name: Run Always
        if: ${{ always() }}
        run: echo "!fromJson(env.isActorDependaBot)==> ${{ !fromJson(env.isActorDependaBot) }}"
      - name: Run Always 2
        if: ${{ always() }}
        run: echo !env.isActorDependaBot==> ${{ !env.isActorDependaBot }}

  conditional_job2:
    if: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!!"
        if: ${{ env.isMainBranch == 'false' }}
      - run: echo "Hello World 2!!" ${{ toJson(env.isActorDependaBot) }}
        if: ${{ env.isActorDependaBot == 'true' }}  #This works and step is skipped

  job1:
    name: fromJSON example
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

      - name: Environment Variables
        run: |
            env | sort
            echo ${{ github.ref }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
