name: github-cli

on:
  workflow_dispatch: # enables manual triggering of this workflow run
  push: 
    paths: 
      - ".github/workflows/gh-cli.yml"

jobs:
  cli: # explore github cli commands and authentication & GITHUB_TOKEN permissions
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # this also works
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo env.GH_TOKEN ==> ${{env.GH_TOKEN}}
          echo github-token: ${{ github.token }}.
    
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - name: checkout the repository as to list the issues in next step, we've to be in repo context
        uses: actions/checkout@v4
      - run: gh issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows
