name: github-token-usage

on: 
  workflow_dispatch: 

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title - ${{ github.run_number}}" --body "Sample Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}