name: github-token-usage

on: 
  workflow_dispatch: 
permissions: read-all

jobs:
  job:
    runs-on: windows-latest
    steps:
      - name: print pwd
        run: |
          echo $pwd
          pwd
          dir
        shell: powershell
      - run: (Get-Date).ToString("hh:mm:ss tt")
      - name: Sleep for 90 seconds
        run: Start-Sleep -s 90
        shell: powershell
      - run: (Get-Date).ToString("hh:mm:ss tt")
        
  job1:
    runs-on: windows-latest
    steps:
      - name: print pwd
        run: |
          pwd
          cd ..
          pwd
        shell: powershell
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title - ${{ github.run_number}}" --body "Sample Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }} and ${{github.run_number}}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_. \n\n The Workflow run_number is: _${{github.run_number}}_"
            }' \
          --fail          