name: make-file-test

on: 
  workflow_dispatch: 

jobs:
  make_file_test:
    runs-on: ubuntu-latest
    name: make-file-test
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: create cache directory
        run: mkdir cache
      - run: make create-cache
      - run: |
          ls -r
          echo "$(cat hello_world.txt)"
        name: print cache folder
        working-directory: ./cache  
      - name: run make file target
        run: |
          ls -R
          make clear-cache
      - name: print ${{github.workspace}} directory after clear-cache
        run: |
          ls -R

      - name: copy make file
        run: cp -f Makefile "${{github.workspace}}/make_file_dir"          

      - name: create cache directory
        run: mkdir cache
        working-directory: ${{github.workspace}}/make_file_dir

      - run: make create-cache
        working-directory: ${{github.workspace}}/make_file_dir

      - run: |
          ls -r
          echo "$(cat hello_world.txt)"
        name: print cache folder
        working-directory: ${{github.workspace}}/make_file_dir/cache  
