name: make-file-test

on: 
  workflow_dispatch: 

jobs:
  make_file_test:
    runs-on: ubuntu-latest
    name: make-file-test
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: run make file target
        run: |
          ls -R
          make clear-cache
