name: Test matrix
on: 
    # push:
    workflow_dispatch:

jobs:
  job_one:
    runs-on: ${{ matrix.os }}
    outputs:
      MATRIX_OUTPUT: ${{ toJson(matrix) }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    steps:
    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: ${{ matrix.node }}
    #   - name: Output node version
    #     run: node --version
      - name: print matrix values
        run: |
          echo "[os: ${{ matrix.os }}] [node: ${{ matrix.node }}]"   
          echo "${{ toJson(matrix) }}"   
       