name: Test matrix
on: 
    # push:
    workflow_dispatch:

jobs:
  job_one:
    outputs:
      key_${{ matrix.os }}: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    steps:
    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: ${{ matrix.node }}
    #   - name: Output node version
    #     run: node --version
      - name: print matrix values
        run: |
          echo "[os: ${{ matrix.os }}] [node: ${{ matrix.node }}]"   
          echo "${{ toJson(matrix) }}"   

  job_two:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option1: ["value1", "value2"]
    outputs:
      ${{ matrix.option1 }}-output: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"          