name: github-output-check

on:
    workflow_dispatch: 
    
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo ${{ github.ref }}
          echo "GITHUB_OUTPUT ==> $GITHUB_OUTPUT"
          echo "GITHUB_OUTPUT ==> " $GITHUB_OUTPUT
          echo "GITHUB_ENV:= $GITHUB_ENV"
      - id: step2
        name: set github_env_path variable into $GITHUB_ENV
        run: echo "github_env_path=$GITHUB_ENV" >>$GITHUB_ENV
      - id: step3
        name: using github_env_path
        run: echo ${{env.github_env_path}}
      - name: print "$GITHUB_ENV"
        id: step4
        run: echo "$(cat ${{env.github_env_path}})"              

  job01:
    runs-on: windows-latest
    steps:
      - id: step1
        run: |
          echo ${{ github.ref }}
          echo "GITHUB_OUTPUT ==> $env:GITHUB_OUTPUT"
          echo "GITHUB_OUTPUT ==> " $env:GITHUB_OUTPUT
          echo "GITHUB_ENV:= $env:GITHUB_ENV"
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: print_github_output
        run: echo "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - id: step3
        run: |
          echo "GITHUB_ENV:= $GITHUB_ENV"
          echo "updated GITHUB_OUTPUT file of STEP1: $(cat $GITHUB_OUTPUT)"
          echo ${{ steps.step1.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}-O1
          OUTPUT2: ${{needs.job1.outputs.output2}}-O2
        run: echo "$OUTPUT1 $OUTPUT2"