on: 
  workflow_call: 
    inputs:
      build_configuration:
        description: dotnet build configuration i.e. Debug or Release
        type: string
        required: true
      environment:
        description: Github environment for deployment
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
    build:
        defaults:
          run:
            working-directory: ./api
        name: dotnet release build & upload
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: dotnet --list-runtimes
          - run: dotnet --list-sdks
          - run: dotnet build --configuration ${{inputs.build_configuration}}
          - run: dotnet test
        #   - run: ls -R
          - name: upload-api-single-file
            id: upload-api-single-file
            uses: actions/upload-artifact@v4
            with:
              name: api_dll
              path: ./api/**/bin/Release/**/api.dll
              include-hidden-files: true
          - name: Output artifact ID
            run:  echo 'Artifact ID is ${{ steps.upload-api-single-file.outputs.artifact-id }}'  
        

