name: reusable-test

on: 
  workflow_dispatch: # manual triggering

env:
  APP_NAME: GHA_PRACTICE

jobs:
  call_build:
    name: call-build-flow
    uses: ./.github/workflows/reusable-api-build.yml
    secrets: inherit
    with:
      build_configuration: Release
      environment: dev
  deploy:
    name: call-deploy-flow
    needs: 
      - call_build
    uses: ./.github/workflows/reusable-api-deploy.yml
    secrets: inherit
    with:
      environment: dev
