on: 
  workflow_call: 
    inputs:
      environment:
        description: Github environment for deployment
        type: string
        required: true      
      application_name: 
        description: Application Name for deployment
        type: string
        required: true
      stage:
        description: The stage of the app to deploy to
        required: true
        type: string
      region:
        description: The region to deploy to
        required: true
        type: string

defaults:
  run:
    shell: bash
    
jobs:
  deploy:
    name: download build artifact from reusable build call flow for ${{inputs.environment}}
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: api_${{inputs.environment}}
          path: '.'
      - name: Print Artifact Files
        run: ls -R
      - name: Download ${{inputs.application_name}} Artifact
        uses: actions/download-artifact@v4
        with:
          name: app_${{inputs.environment}}
          path: '.'
      - name: Print ${{inputs.application_name}} Artifact Files
        run: ls -R        