name: setups

on: 
  workflow_dispatch: # manual

jobs:
  setup_serverless:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: check node & npm versions
        run: |
          node --version
          npm --version
