name: setups

on: 
  workflow_dispatch: # manual

env:
  REGION: us-east-1
  STAGE: dev  

jobs:
  detect:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      needs_deployment: ${{ steps.should_deploy.outputs.any_modified }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if should deploy
        id: should_deploy
        uses: tj-actions/changed-files@v41
        with:
          files: |
            .github/**
            api/**
            upper/**
            Makefile
            serverless.yml
  setup_serverless:
    runs-on: ubuntu-22.04
    needs: 
      - detect
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - run: ls -R
        name: print repo files before setup

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Nuget Restore
        run: nuget restore course-gh-actions.sln

      - name: Install Amazon Tools
        run: dotnet tool install --global Amazon.Lambda.Tools

      - name: Build Functions
        run: dotnet-lambda package

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
        #   cache: yarn

      - name: check node & npm versions
        run: |
          node --version
          npm --version
          npm ls
          npm ls -g
      - name: setup serverless
        run: |
          npm install -g serverless@3.39.0
          npm ls 
          npm ls -g
        #   serverless --version

      - run: ls -la
        name: print repo files after setup

      - run: echo $(cat package.json)

      - name: check serverless version
        run: |
          serverless --version
          sls --version
          yarn --version

      - name: run serverless package
        run: make stage=${{ env.STAGE }} region=${{ env.REGION }} package-api
        

        