name: thanks

on: 
  issues: 
    types: 
      - opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    permissions: 
        issues: read
    steps:
      - name: create an issue
        id: issue_script
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          retries: 3
          script: |
            github.rest.issues.get({
                issue_number: context.issue.number || 2,
                owner: context.repo.owner,
                repo: context.repo.repo,
            })          
            console.log(`issue: ${issue}`)
            return context.issue.number + context.repo.owner + context.repo.repo
      - run: echo ${{ steps.issue_script.outputs.result }}
          