name: thanks

on: 
  issues: 
    types: 
      - opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    permissions: 
        issues: read
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)

      - name: create an issue
        id: issue_script
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          retries: 3
          script: |
            const issue_number = context.issue.number || 2
            const issue = await github.rest.issues.get({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
            })          
            console.log(`issue: ${JSON.stringify(issue)}`)
            return issue_number + context.repo.owner + context.repo.repo
      - run: echo ${{ steps.issue_script.outputs.result }}
          