name: thanks

on: 
  issues: 
    types: 
      - opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - name: create an issue
        id: issue_script
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          retries: 3
          script: |
            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return context.issue.number
          