name: thanks

on: 
  issues: 
    types: 
      - opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    permissions: 
        issues: read
    steps:
      - name: create an issue
        id: issue_script
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          retries: 3
          script: |
            return context.issue.number + context.repo.owner + context.repo.repo
          