name: upper-build

# run-name: Deploy by @${{ github.actor }}

on:
    push: 
        paths: 
            - ".github/workflows/upper-build.yml"
            - "upper/**"

jobs:
    build:
        name: "go-project-upper-build"
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - name: "check-out-repo"
              uses: actions/checkout@v4
            - run: pwd && ls -R

            # Step with a name
            - name: "print go version"
              run: go version
            - uses: actions/setup-go@v5
              with:
                # go-version: '1.22'
                go-version-file: ./upper/go.mod
                cache-dependency-path: ./upper/go.sum
            - name: "print go version after setting up 1.22"
              run: go version
            - name: "download go dependencies"
              run: go mod download
              working-directory: ./upper

            - name: "build & test go"
              id: buildAndTest
              run: |
                pwd
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: ./upper

            - name: "print dotnet runtimes and SDK versions"
              id: printDotNetEnvDetails
              run: |
                pwd && dotnet --list-runtimes
                dotnet --list-sdks

            - name: "setup dotnet"
              uses: actions/setup-dotnet@v4
              id: setupDotnetId
              with:
                dotnet-version: '6.0.x'
            - run: echo '${{ steps.setupDotnetId.outputs.dotnet-version }}' # outputs 3.1.422
            - run: dotnet --list-runtimes
            - run: dotnet --list-sdks                
